apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - namespace.yaml
  - service-accounts.yaml
  - pvcs.yaml
  - postgres-config.yaml
  - postgres.yaml
  - redis.yaml
  - deployment.yaml
  - httproute.yaml

# KSOPS generator for decrypting SOPS-encrypted secrets
generators:
  - ksops-generator.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: nextcloud
    includeSelectors: false

images:
  - name: nextcloud
    newTag: 30-apache
  - name: postgres
    newTag: 16-alpine
  - name: redis
    newTag: 7-alpine
